### ISSUE TITLE
Commenting your code

### ISSUE THREAD

**Issue by zannain** [codebyanya/TeaCozy#3]
Get into the habit of commenting your code, you will thank yourself later when you return to code that you wrote some time ago. I noticed that you organized your code by prefixing class names with `middle` `bottom` and `header`. See my other Github issue about naming conflicts but another suggestion is to add comments throughout your code that tell you what a section of code is doing. This will help anyone reading your code know exactly what a portion of your code is doing, it will help you bring yourself up to speed when you return to some web page that you wrote some time ago as opposed to working your way down from the top. 

```css
/* Styles applied here are for navigation */
nav {
 display: flex;
}

/* Article styles */
section {
 background: #000;
}

/* Footer styles */
footer {
 margin:10px;
}
```

https://github.com/codebyanya/TeaCozy/blob/master/resources/css/style.css#L160-L173
